const PAGE = ['HOME', "LADDINGPAGE"]

const SECOND_PER_MIN = 60;
const SECOND_PER_HOUR = SECOND_PER_MIN * 60;
const SECOND_PER_DAY = SECOND_PER_HOUR * 24;
const SECOND_PER_WEEK = SECOND_PER_DAY * 7;

export {
  PAGE,
  SECOND_PER_MIN,
  SECOND_PER_HOUR,
  SECOND_PER_DAY,
  SECOND_PER_WEEK
}